apiVersion: v1
kind: Service
metadata:
  name: ingress-wildcard-host
spec:
  ports:
  - port: 8080
    name: web
  clusterIP: None
  selector:
    app: app-name
---
apiVersion: apps/v1
kind: StatefulSet
## TODO: Complete the rest